#!/usr/bin/env python
"""
Monkey Studio free crossplatform IDE.
Main file processes command line arguments and starts the system.
"""
import sys
import os.path

import mks.defines

helpString = \
"""
Usage:
\t%s [options] [FILE1 [FILE2 ...]]

Command line arguments:
\t-h, --help      Show command line help
\t-v, --version   Show program version
"""


def showHelp():
    showVersion()
    print helpString % sys.argv[0]
    

def showVersion():
    print "%s version %s" % (mks.defines.PACKAGE_NAME, mks.defines.PACKAGE_VERSION)
    print mks.defines.PACKAGE_COPYRIGHTS
    print "http://%s" % mks.defines.PACKAGE_DOMAIN

def main():
    if '-v' in sys.argv or '--version' in sys.argv:
        showVersion()
        return 0
    
    if '-h' in sys.argv or '--help' in sys.argv:
        showHelp()
        return 0
    
    try:
        import PyQt4
    except ImportError:
        print >> sys.stderr, 'Failed to import PyQt4 bindings'
        print >> sys.stderr, 'Try to install python-qt4 package, or download sources from ' + \
                             'http://www.riverbankcomputing.co.uk/pyqt/download'
        return -1

    import PyQt4.QtGui
    app = PyQt4.QtGui.QApplication ( sys.argv );
    
    try:
        import PyQt4.Qsci
    except ImportError:
        from PyQt4.QtGui import QMessageBox
        QMessageBox.critical(None, "QScintilla not found",
                                "Failed to import QScintilla 2 python bindings.\n"
                                "Try to install python-qscintilla2 package, or download sources from "
                                "See http://github.com/hlamer/Fresh-framework/archives/master for installation instructions")
        return -1
    
    try:
        import PyQt4.fresh
    except ImportError, ex:
        from PyQt4.QtGui import QMessageBox
        QMessageBox.critical(None, "Fresh not found",
                                "Failed to import Fresh framework. Probably it is not installed.\n" +
                                str(ex) + '\n' +
                                "Check for installation instructions"
                                "http://www.riverbankcomputing.co.uk/software/qscintilla/download")
        return -1
    
    # Imports only here. Hack for ability to get help and version info even on system without PyQt and Fresh.
    import mks.defines
    from mks.monkeycore import core
    
    app.setApplicationName( mks.defines.PACKAGE_NAME );
    app.setOrganizationName( mks.defines.PACKAGE_ORGANISATION );
    app.setOrganizationDomain( mks.defines.PACKAGE_DOMAIN );
    
    app.lastWindowClosed.connect(app.quit)
        
    """TODO
    support projects and files opening
    """
    
    # init monkey studio core
    core.init();
    
    # Get list of absolute pathes of files to open. List may contain not existing files
    filePathes = [os.path.abspath(arg) for arg in sys.argv[1:]]
    
    for file in filePathes:
        core.workspace().openFile(file)
    
    if core.workspace().currentDocument():
        core.workspace().currentDocument().setFocus()
    
    core.mainWindow().show()
    
    # execute application
    result = app.exec_()
    core.term()
    
    return result

if __name__ == '__main__':
    sys.exit(main())
